### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by xamanu** [grote/osm2gtfs#10]
Currently the filename and path of the output file is hard-coded into the script. We should handle this more generic. Either as another argument on the command line or inside the config file (#3). I prefer the first solution, but before implementing, I wanted to check with you guys.

Cheers!

**Comment by grote** [comment]
I personally prefer as little command-line parameters as possible, but I could imagine that it can be specified in the config file with a command line option to overwrite this value if/when needed.
