### ISSUE TITLE
Support multiple values for the same OSM tag

### ISSUE THREAD

**Issue by AltNico** [grote/osm2gtfs#110]
Maybe this is already supported yet, but in order to be able to [generate national GTFS feeds](https://github.com/grote/osm2gtfs/milestone/1) it is important to be able to specify multiple values for just one OSM tag. This should result in queries that append the different values separated by an *or*.

Example: 
```json
{
    "query": {
        "tags": {
            "network": "NI",
            "network": "NI-Estelí",
            "network": "NI-Managua"
        }
    }
}

**Comment by jamescr** [comment]
I think it's not supported yet. [This Overpass QL example](https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#One_or_another_name) shows the syntax to do it. 

For example a config like:

```json
{
    "query": {
        "tags": {
            "public_transport:version": "2",
            "operator": "Incofer",
            "operator": "Alpizar S.A."
        }
    }
}
```
should create [this query](http://overpass-turbo.eu/s/tVE):
```
relation
  (9.8346,-84.2418,10.0365,-83.8507)
  ["public_transport:version" = "2"]
  ["operator" ~ "Alpizar S.A.|Incofer"];
(._;);
out body;
```
