### ISSUE TITLE
Issues loading bus stops

### ISSUE THREAD

**Issue by bouhormq** [grote/osm2gtfs#162]
Hi! I've been trying to make osm2gtfs pick up bus stops but it's not happening, would really appreciate it if someone could let me know what tags I'm missing here: https://www.openstreetmap.org/node/8188018824

**Comment by nlehuby** [comment]
Hi,

The appropriate tags are `highway=bus_stop` + `public_transport=platform` 

You may want to check out the doc on the wiki : https://wiki.openstreetmap.org/wiki/FR:Bus :wink:

**Comment by bouhormq** [comment]
Hi Noemie! thanks for the help!
