### ISSUE TITLE
Allow route_type as argument

### ISSUE THREAD

**Issue by jamescr** [grote/osm2gtfs#23]
Originally the script was created with bus routes in mind but this could also work for train routes (as the case of incofer train routes)

The idea is to add an optional argumnet:  "--route-type". the default value will be "bus".

**Comment by grote** [comment]
I think the query improvements from #2 will make such a parameter unnecessary.

However, what happens if you want both? trains and busses?

**Comment by jamescr** [comment]
It seems that If I add the "route_type" key/value to the config[query][tags], this issue is unnecessary. 

Regarding to the scenario where I want buses and trains, It's possible but, that case would not be a two GTFS case?

**Comment by xamanu** [comment]
Yes, this seems to me a duplicate, as #2 will allow this. 

IIf you want both in one GTFS, you could still try to find (or come up with) another tag that you put on all relations. Maybe the `network` could be the same. Or in the least and last case you could still come up with a custom tag in OSM: Something like `network:union` or even `gtfs_group` (now people are going to hang me :) ) But if they belong together in a GTFS, then they could also be stated to belong together in OSM. I don't see any problem here.

**Comment by jamescr** [comment]
I got it, will be solved with issue #2 :-)
