### ISSUE TITLE
Default implementation for stops creation

### ISSUE THREAD

**Issue by xamanu** [grote/osm2gtfs#27]
The current stops creation is very much custom for Florianópolis. After the abstraction work happening in (#9)  I'd suggest working on a default implementation for stops generation based on OSM's Public Transport Schema 2.

Managua can be a good start as the data quality is very consistent and complying the standard data structure without exceptions.

**Comment by grote** [comment]
It would be nice, if you could make a list where the current implementation deviates from a proper default.

**Comment by xamanu** [comment]
This is very much related to #26, but is a different issue so we can have two smaller pull requests each. But probably the main discussion is going to happen in the other issue. Here it's more about stop specific stuff.

As I said in #26 I haven't started thinking too much about it. And this issue is not to say, that all of Fenix has to be different in the default implementation. We just have to look at it and decide which parts are generic and which aren't.

But for sure the name finding part for stops without a name is very particular to Fenix. The default implementation would probably assume to have bus stop names for all stops in OSM already.

I guess as we move on, more things will be figured out and can be discussed here.

**Comment by xamanu** [comment]
Actually if `TripsCreatorFenix` logic implemented pulling `Stop` objects from `data.stops` based on the stop ids in `Route.stops`, then Fenix could use the currently proposed default `StopsCreator` implementation and get rid of the  functions `add_stops_to_routes()` and `_fill_stops()`

**Comment by grote** [comment]
Good idea!
