### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by xamanu** [grote/osm2gtfs#38]
Currently we have the following folder (package) structure

- `creators` (extendible part of the application)
- `factory` (handles logic to for the creators)
- `osmhelper` (everything else: OsmConnector, Cache, data structure)
- `data` (data caching, input and output)
- `src` (external python packages)

I'm proposing to merge `factory` and `osmhelper` into one single package called `core`. What do you think?

**Comment by xamanu** [comment]
And I also suggest to rename `osm_routes.py` to `routes.py` and `osm_stops.py` to `stops.py`. They are not specific to OSM anymore (especially after #30). They are _just_ the data structure. Isn't this more beautiful?

**Comment by grote** [comment]
I don't mind merging the factories and the osm classes into one package.

> And I also suggest to rename osm_routes.py to routes.py and osm_stops.py to stops.py

This is how I had it before. The reason I renamed things to `osm_` is because `routes` and `stops` are frequently used as variable names in the code which then overshadow the imported routes and stops.

**Comment by xamanu** [comment]
We use `stops` and `routes` variables for containers (dictionaries) holding objects of classes defined in (osm_)`stops.py` and  (osm_)`routes.py`. Isn't this logical to name them equally?
