### ISSUE TITLE
Improve debugging

### ISSUE THREAD

**Issue by xamanu** [grote/osm2gtfs#46]
Debugging, such as screen output and special functions like `Route.print_shape_for_leaflet()` are currently within regular code. I'd like to optimize this. Right now I'm thinking about:

* a `Debug` class for special functions 
* making debug print output always depending on a flag (probably set through a bash argument)

**Comment by xamanu** [comment]
There is some [ongoing work here](https://github.com/xamanu/osm2gtfs/tree/issue-46-debug). Still in progress.

**Comment by grote** [comment]
Why not use the [Logger](https://docs.python.org/2/library/logging.html) class?

**Comment by xamanu** [comment]
Good questions. Logger looks exactly like what I wanted to achieve. Let's go for this one.

**Comment by Skippern** [comment]
I have user Logger on other projects, the only feature I miss is the ability to maintain multiple log files. Good thing is that dependencies using Logger will also be included in the log file, i.e. `requests`

**Comment by xamanu** [comment]
I gave it a try with this PR: #142

**Comment by xamanu** [comment]
This has been [merged in](https://github.com/grote/osm2gtfs/commit/210f65e8c7dfdaa82a8094ff5bac5e0259c1ee43). Thanks for the review @grote.
