### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by xamanu** [grote/osm2gtfs#52]
We need documentation on how the script works, which functionalities it has and how the config file is structured. I suggest to use the wiki here in this github repo.

**Comment by xamanu** [comment]
Here we go. The first draft for configuration:

* https://github.com/grote/osm2gtfs/wiki
* https://github.com/grote/osm2gtfs/wiki/Configuration

**Comment by grote** [comment]
Awesome @xamanu, thanks a lot! :)

**Comment by xamanu** [comment]
I guess we can close here.
