### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by xamanu** [grote/osm2gtfs#53]
We need documentation on how the script is technically structured, how to extend the script and how to make it work for other cities and other type of schedule information. I suggest to use the wiki here in this github repo.

**Comment by grote** [comment]
@marcosfede when adapting osm2gtfs for your own region, you need to provide your own creators for routes, stops and trips. Have a look at [the `creators` folder](https://github.com/grote/osm2gtfs/tree/master/creators). There you have (incomplete) default implementations for those creators and a `fenix` folder where specific creators for the fenix transport agency are stored.

Essentially, these merge the data retrieved from OSM with schedule data that you have to provide yourself. Normally, schedules are published somewhere, ideally in a machine readable format. Many people scrape websites as well to get the schedules. 

You would start by taking the [example config file](https://github.com/grote/osm2gtfs/blob/master/fenix.json.example) and adapt it to your region. Then you can run the script to fetch and cache data from OSM. Based on that data you can then work on combining it with the schedule information similar to how it is done for fenix. Another example you can look at is the [incofer agency from Costa Rica](https://github.com/jamescr/osm2gtfs/tree/master/creators/incofer) which is not yet merged.

**Comment by marcosfede** [comment]
Sounds good. I'll take a look at this in the following days If I can get the data from somewhere. Thanks!

**Comment by xamanu** [comment]
I just added some documentation:

* https://github.com/grote/osm2gtfs/wiki
* https://github.com/grote/osm2gtfs/wiki/Configuration
* https://github.com/grote/osm2gtfs/wiki/Development

**Comment by jamescr** [comment]
Thanks @xamanu !!!

**Comment by xamanu** [comment]
I guess we can close this one here.
