### ISSUE TITLE
Grouping stops

### ISSUE THREAD

**Issue by jamescr** [grote/osm2gtfs#55]
I'm testing Transportr (a locally compiled version) with incofer data and I notice that some stops are avoided as line change points. Example: instead of changing from line 2 to line 4 in stop A is being done in stop B affecting times of the total trip. I suspect maybe that non grouped stops could be the problem, as stop A of line 2 and stop A of line 4 aren't exactly in the same point but are in the same station:

-84.0693107,Estación Atlántico,9.9349735,4310018677,0
-84.0686079,Estación Atlántico,9.9346699,4628999925,0

Adding support for grouping stops (stations) in the GTFS file seems simple. The GTFS part is solved using the parent_station and location_type of the stops.txt (https://developers.google.com/transit/gtfs/reference/stops-file). And from OSM we could check for the stop_area relation the contains both  stop_position. At the end we should have something like this:

stop_lon,stop_name,stop_lat,stop_id,location_type, parent_station
-84.0693107,Estación Atlántico,9.9349735,4310018677,0, ID
-84.0686079,Estación Atlántico,9.9346699,4628999925,0, ID
lon, Estación Atlántico, lat, ID, 1,

**Comment by grote** [comment]
Strange that it doesn't tell you to walk from stop A2 to stop A4.

But in general, I agree that we should have support for parent_stations and stop_area relations.

Your dataset should be sufficiently small to add the parent station manually and see if that helps with the problem. Maybe it is worth a try.

**Comment by jamescr** [comment]
With the stops grouped in a station Transportr tell me to walk from stop A2 and A4, and the results make more sense. Here are the results:

![photo_2017-02-10_14-42-34](https://cloud.githubusercontent.com/assets/593829/22843554/c45aa866-ef9f-11e6-8291-8aee1c199022.jpg)

![photo_2017-02-10_14-42-43](https://cloud.githubusercontent.com/assets/593829/22843555/c46027e6-ef9f-11e6-8437-1e6de28104ca.jpg)

**Comment by grote** [comment]
Thanks for the screenshots. Looks good. If you want to work on this, maybe let's merge your incofer branch first. It seems to be in a usable state already.

**Comment by jamescr** [comment]
Sure I'll work on this issue.

You mean the incofer branch of public-transport-enabler and Transportr ?

**Comment by grote** [comment]
> Sure I'll work on this issue.

Awesome! :)

> You mean the incofer branch of public-transport-enabler and Transportr ?

No, I meant the incofer provider for osm2gtfs.

**Comment by jamescr** [comment]
Honestly I wasn't expecting to merge it, but if you agree I think it's great!.

**Comment by grote** [comment]
In my opinion, all other creators should ideally be merged here. This makes sense for example when we refactor the code. If the creators live in other repositories, they need to be manually adjusted to whatever changed in the upstream repository.

**Comment by jamescr** [comment]
I have a working draft for this issue: https://github.com/jamescr/osm2gtfs/tree/issue-55. Now It's only working for Incofer but I'll appreciate any comment before extending it to fenix. By the way i have one doubts about stop/stop_areas, a OSM stop/platform could be member of more than one stop_area?

**Comment by grote** [comment]
Great! :)

Just [gave it a quick look](https://github.com/jamescr/osm2gtfs/compare/incofer...jamescr:issue-55) and I wonder whether it is necessary to make an extra query per stop_area. Couldn't this data be returned by @xamanu's new optimized query?

**Comment by jamescr** [comment]
The problem with the stop_area is that those aren't part of the relations that describe a route. Stops and platforms are part of a stop_area relation. Anyway I'll look at @xamanu query to be sure if I could reused it.

**Comment by jamescr** [comment]
I have implemented an [alternative solution](https://github.com/jamescr/osm2gtfs/tree/issue-55b) that uses the _query_stops() with a little modification to get the stop_areas. Also includes a different approach on handling stops (similar in some way to the routes variants and masters).  Again I have been testing with incofer but this is only a request for comments draft.

**Comment by grote** [comment]
Nice! I didn't review it, but looks like with this solution, you don't need to make additional queries. Great!
Do you personally prefer this solution over the other one?

**Comment by jamescr** [comment]
Yes I think the alternative solution is better. I hope I could finish it by the end of the week.
