### ISSUE TITLE
Incofer provider

### ISSUE THREAD

**Issue by jamescr** [grote/osm2gtfs#56]
I'm creating this issue just to keep issue#55 with the original theme. 

> In my opinion, all other creators should ideally be merged here. This makes sense for example when >we refactor the code. If the creators live in other repositories, they need to be manually adjusted to 
> whatever changed in the upstream repository.

Make sense to keep the creators in the same repo, also if we try to make generic default creators will be very useful to have them together. 

And what about config files? A config folder to keep them could be a solution. What you think?

**Comment by grote** [comment]
There could be a dedicated folder for them, but they could also just be in the creator's folder like for example here for fenix: https://github.com/grote/osm2gtfs/tree/master/creators/fenix
