### ISSUE TITLE
Automatic start_date generation error

### ISSUE THREAD

**Issue by jamescr** [grote/osm2gtfs#60]
There is a validation error when start_date is automatically generated:

~~~
transitfeed.problems.InvalidValue: Invalid value 2017301 in field start_date
~~~

This is because datetime.datetime() returns the numer of the month as one digit (3) instead of two (03).

**Comment by jamescr** [comment]
There was also a problem with end_date automatically generation. I hope had [fixed both](https://github.com/jamescr/osm2gtfs/tree/issue_60), but when running fenix config I'm getting a lot of messages like:

~~~
Exception weekday for 2015-12-25 00:00:00
~~~

I'm not sure what is that about but I'll take a look at that latter.

**Comment by jamescr** [comment]
> I'm not sure what is that about but I'll take a look at that latter.

Seems to me there is nothing there, just the normal operation of fenix trips creator. 

I had not run it in a while.   :smile:

**Comment by grote** [comment]
> Seems to me there is nothing there, just the normal operation of fenix trips creator.

These are just some left over debug statements, because I am still testing the support for schedule exceptions ;)
