### ISSUE TITLE
script isn't compiling my creators

### ISSUE THREAD

**Issue by xirapo** [grote/osm2gtfs#64]
I've been working on the script and building the creators for my city and i noticed that if i run the 
script with the :

> --refresh-all flags it work fine 
but if i try to run it with out the flag the script doesn't work and i raise the " Should have implemented this"
like  in the route_creator and in trips_creator.

so that tells me the script is not reading my creators and in my config.json i did specify the selector 

> "selector" : "irtramma" 

any ideas why is this happening?  i did run incofer with the data that james has in one of his repos and  works fine.

**Comment by grote** [comment]
Could you please let me know which code you are trying to run with what command exactly?

**Comment by xirapo** [comment]
`python osm2gtfs.py -c creators/irtramma/irtramma.json`

thats the one im trying to run.

**Comment by grote** [comment]
Thanks! That's the command. But what code do you run this on? This repo for example doesn't have a `creators/irtramma/irtramma.json` file.

**Comment by xirapo** [comment]
i have a fork of the repo and  i've been working there and i create a dir call irtramma and inside irtramma i have my 3 creators . 

`{
    "query": {
        "bbox": {
            "n": "12.21",
            "s": "12.04",
            "e": "-86.12",
            "w": "-86.38"
        },
        "tags": {
            "route":"bus",
            "network": "IRTRAMMA",
            "public_transport:version": "2"
        }
    },
    "agency": {
        "agency_id": "NI-Irtramma",
        "agency_name": "Instituto Regulador del Transporte del Municipio de Managua",
        "agency_url": "http://www.managua.gob.ni/",
        "agency_timezone": "America/Managua",
        "agency_lang": "es",
        "agency_phone": "+505 255-2189",
        "agency_fare_url": ""
    },
    "feed_info": {
        "publisher_name": "Mapanica",
        "publisher_url": "http://mapanica.net",
        "version":  "0.1",
        "start_date": "20161101",
        "end_date": "20171031"
    },
    "output_file": "data/ni-managua.zip",
    "selector": "irtramma"
}
`
this is the irtramma.json im using.

**Comment by jamescr** [comment]
We have successfully [fixed](https://github.com/xirapo/osm2gtfs/commit/92c047d6517f16562a0871497061a408a877093b) this issue.

**Comment by grote** [comment]
Thanks for helping @jamescr! :)
