### ISSUE TITLE
GTFS creation only using OSM data

### ISSUE THREAD

**Issue by proma90** [grote/osm2gtfs#67]
Hi,

I'm writing here not sure if it is the right place, so sorry in advance for that. I've installed osm2gtfs because I need to generate GTFS data from Birmingham and Newcastle (uk), but there is no GTFS information anywhere. 

My question is if it is possible to create GTFS data for these cities only having OSM data. If it is possible, there is information/guide to follow?

Thank you,

Proma

**Comment by grote** [comment]
OSM data can only give you the geography of the public transport. This is what osm2gtfs automates. What is missing is the schedule information. This you need to provide yourself somehow.

**Comment by proma90** [comment]
In what format do they have to be?

**Comment by grote** [comment]
Currently, we feed in the schedules via small python classes. You could write one for your XML. Otherwise, we are discussing a JSON based default format right now in #62.
