### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by jaullo** [grote/osm2gtfs#86]
Hello to all,

I'm very interested in this project. So thanks to the authors.
Can u upload again the json files, for example incofer.json for costa rica?
I have checked all links but are dead

Thanks

**Comment by xamanu** [comment]
The timetable information

* for Fenix: http://www.consorciofenix.com.br/api2/linhas.json
* for Incofer: https://raw.githubusercontent.com/jamescr/incofer-datos/master/input_incofer.json
* for Accra: No need for external timetable information.

**Comment by jaullo** [comment]
Thank u so much!
