### ISSUE TITLE
Upgrade transitfeed library and remove feed_info workaround

### ISSUE THREAD

**Issue by grote** [grote/osm2gtfs#90]
google/transitfeed#394 has been merged and released as `1.2.16`.The workaround in the code to add the `feed_info.txt` manually should be removed now.

Also, Accra regression tests need to be fixed. There are different stop times now.

**Comment by grote** [comment]
A new version has been released: https://pypi.python.org/pypi/transitfeed

The work-around should be removed now and we should depend on the latest version.

**Comment by grote** [comment]
@nlehuby or @prhod when you get a chance, could you please look into why the `transitfeed` upgrade changes your gtfs zip and maybe package a new one for now?

**Comment by prhod** [comment]
HI @grote ! I'll try to have a look soon. Note to self : only the stop_times.txt file is different.

**Comment by prhod** [comment]
Looking further, I have differences in stop_times. For example, trip_id 82 takes 15' from end to end and the expected travel time is 2 hours. I still need to investigate.

**Comment by prhod** [comment]
I don't know why I had differencies before, I don't have anymore. Maybe I mixed up my working files ...
Anyway, I made the PR https://github.com/grote/osm2gtfs/pull/122 to upgrade to the last version of Transitland. The only difference was the addition of the "timepoint" column in the stop_times.txt file.

**Comment by xamanu** [comment]
The associated PR has been merged. Can this issue be closed, @grote? Thanks!
