### ISSUE TITLE
GTFS stop_id and mapping to OpenStreetMap

### ISSUE THREAD

**Issue by xamanu** [grote/osm2gtfs#94]
Currently the `stop_id` for the GTFS is extracted based on the `id` coming from OpenStreetMap. This is nice, because ideally it allows mapping between a stop and its object in OpenStreetMap.

Some context: OSM has three types of [elements](http://wiki.openstreetmap.org/wiki/Elements): node, way, relation. They have separate spaces for IDs:

>  Element types have their own ID space, so there could be a node with id=100 and a way with id=100, which are unlikely to be related or geographically near to each other.

Currently it seems to work like this (in the [standard stop creator](https://github.com/grote/osm2gtfs/blob/1e266b87499d692337d62ab5097be45748a33d22/osm2gtfs/creators/stops_creator.py)): if the stop is a node or a way it gets it's ID (even though they are not the same). If it is a relation of type `stop_area`, then a `SA` gets prepended to the ID.

This is not ideal, because IDs should be solid (and not change over time), and they should not conflictive (like IDs between nodes and ways).

**Comment by xamanu** [comment]
Usually in OpenStreetMap the following schema is used: `[element_type]/[id]`

* `node/[id]`
* `way/[id]`
* `relation/[id]`

**Comment by xamanu** [comment]
@prhod, @nlehuby, @grote, @AltNico, @jamescr, what do you think?

**Comment by xamanu** [comment]
There have been ideas to use WikiData for the source of truth for bus stops and their IDs. But I guess currently this would be an overhead. (cc @leofrachet)

**Comment by nlehuby** [comment]
I think it's fine to use OSM id as GTFS stop_id.
I would rather choose `n[id]`, `w[id]` and `r[id]`, which 
* is another usual schema in OSM
* is shorter 
* does not contain any special character

**Comment by grote** [comment]
Whatever we choose, there should be a way to override this for existing creators, so they can keep their current schema. For example, there could be a `get_id()` method in the stop creator that gets a `Stop` object and returns a string representation of the ID. Creators can then override the method.

**Comment by xamanu** [comment]
Yes,  I agree with @nlehuby proposal to use fully-unique IDs by prefixing each OSM ID with the first letter of the entity type.

> Whatever we choose, there should be a way to override this for existing creators, so they can keep their current schema.

Sure, stop creators can be overridden easily overwrite this.

**Comment by xamanu** [comment]
I'm happy to provide a patch within the Pull Request for the other standard creators. In order to be able to work on it efficiently, I'm kindly pushing to get those PRs into osm2gtfs: #91 and #89

**Comment by xamanu** [comment]
Just a comment, I just found in the [osm_connector](https://github.com/grote/osm2gtfs/blob/master/osm2gtfs/core/osm_connector.py) that we are using the format `node/[id]`, etc., already.

**Comment by xamanu** [comment]
For now I stuck with the format which was used before (somebody may want to change it later, but I don't want to explode the PR #96). However I made it more easily overrideable by any `stops_creater` by just implementing `get_gtfs_stop_id`. Here is a [proposal](https://github.com/mapanica/osm2gtfs/blob/e917f6a12aacfad12453cc53dc9031dc5e92b2be/osm2gtfs/creators/stops_creator.py)

**Comment by xamanu** [comment]
This can be closed now: Creators have now a mechanism to define their GTFS ID and we have a standard ID which doesn't mix up OSM types anymore. In case any change needed to be done please would you open a respective issue for it.
